### ISSUE TITLE
issue with id and password set

### ISSUE THREAD

**Issue by Ragavmuralidharan** [treydock/tsm_exporter#42]
Hi could you let me know where the id and password should be put.. no information on the site.

**Comment by treydock** [comment]
See configuration examples: https://github.com/treydock/tsm_exporter#configuration.  The id and password are in the configuration file.

**Comment by Ragavmuralidharan** [comment]
Hi Thanks i think i am missing lot of configuration and missing installations. Is there any in details document how to set this up like installation requirement. I really appreciate your work on this, i am new to this trying to figure out how can set one for our environment. 

Also is there a possible way to provide backup status ?

Thanks

**Comment by treydock** [comment]
This tool only works with Prometheus, so you need Prometheus to query this tool.  The README covers the install of this tool, Prometheus and things needed for that are outside the scope of this project's documentation.
